let SOC={alerts:{rows:[],severity:{},trend:[]},enterprise:{rows:[]},ledger:{rows:[],nodes:[]},posture:{modules:{},mitre:{techniques:{},tactics:{}},compliance:{rows:[],passed:0,failed:0},vulnerabilities:[],fim:[]}}, socWindow='all', huntText='', huntSeverity='all', socLoading=false;
const severity=l=>Number(l)>=12?'critical':Number(l)>=8?'high':Number(l)>=5?'medium':'low';
const pill=(text,type='unknown')=>`<span class="pill ${type}">${esc(text)}</span>`;
const fmtTime=t=>t?new Date(t).toLocaleString(): 'Not reported';
function goSoc(k){document.querySelector(`#nav button[data-k="${k}"]`)?.click();}
function socHeader(title,subtitle){return `<div class="soc-heading"><div><div class="eyebrow">DN-Hacks / Energy & infrastructure / Security operations</div><h2>${title}</h2><div class="muted">${subtitle}</div></div><div class="soc-controls"><select aria-label="Alert time range" onchange="socWindow=this.value;loadSoc()"><option value="all" ${socWindow==='all'?'selected':''}>All indexed history</option><option value="24h" ${socWindow==='24h'?'selected':''}>Last 24 hours</option><option value="7d" ${socWindow==='7d'?'selected':''}>Last 7 days</option></select><button class="soc-button" onclick="loadSoc()">↻ Refresh</button></div></div>`;}
function metric(label,value,hint,cls=''){return `<div class="metric ${cls}"><div class="label">${label}</div><div class="value">${value??'—'}</div><div class="hint">${hint}</div></div>`;}
function alertRows(rows){return rows.map(a=>{const i=SOC.alerts.rows.indexOf(a);return `<tr><td>${pill(severity(a.rule?.level),severity(a.rule?.level))}</td><td><button class="link" onclick="inspectAlert(${i})">${esc(a.rule?.description||'Untitled detection')}</button><div class="subline">Rule ${esc(a.rule?.id||'—')} · ${esc((a.rule?.groups||[]).slice(0,3).join(' / '))}</div></td><td>${esc(a.agent?.name||'Manager / unspecified')}</td><td class="mono">${esc(fmtTime(a.timestamp))}</td><td>${pill('Indexed','live')}</td></tr>`}).join('')||'<tr><td colspan="5" class="empty">No matching alerts. Adjust the query or time range.</td></tr>';}
function alertTable(rows){return `<table class="soc-table"><thead><tr><th>Severity</th><th>Detection</th><th>Endpoint</th><th>Observed</th><th>Source</th></tr></thead><tbody>${alertRows(rows)}</tbody></table>`;}
function renderSoc(){
 const a=SOC.alerts,l=SOC.ledger, counts=a.severity||{},total=a.total||0, trend=a.trend||[];
 const latestEnterprise=(SOC.enterprise?.rows||[])[0],latestRequest=latestEnterprise?.envelope?.request||{},latestId=latestEnterprise?.request_id;
 const correlated=(l.rows||[]).filter(row=>row.request_id===latestId),latestDecision=correlated.find(row=>row.event_type==='DECISION'),latestExecution=correlated.find(row=>row.event_type==='EXECUTION_RESULT');
 const latestOutcome=latestExecution?.event?.detail?.outcome||latestDecision?.event?.detail?.outcome||'RECEIVED';
 const max=Math.max(1,...trend.map(x=>x.doc_count));
 const bars=trend.length?trend.map(b=>`<i style="height:${Math.max(3,b.doc_count/max*100)}%" title="${esc(b.key_as_string)}: ${b.doc_count} alerts"></i>`).join(''):'<div class="empty">No indexed events in this interval</div>';
 $('s-soc').innerHTML=socHeader('Security overview','Detection, endpoint visibility and autonomous-agent governance.')+
 `<div class="kpis">${metric('INDEXED ALERTS',a.available?a.total:null,'Selected time range · all severity levels','blue')}${metric('CRITICAL DETECTIONS',a.available?counts.critical:null,'Wazuh rule level 12–15','red')}${metric('ACTIVE VULNERABILITIES',(SOC.posture?.vulnerabilities||[]).length,'Loaded vulnerability detections')}${metric('EDGE AUDIT RECORDS',l.available?l.total:null,'Actual Pi uploads · all indexed history','teal')}</div>
 <div class="soc-grid"><div class="soc-panel"><div class="panel-head">Detection activity <small>Wazuh event-time histogram</small></div><div class="panel-body"><div class="plot" role="img" aria-label="Indexed alerts by time bucket">${bars}</div><div class="plot-label"><span>${esc(trend[0]?.key_as_string?.slice(0,16)||'No data')}</span><span>${esc(trend.at(-1)?.key_as_string?.slice(0,16)||'')}</span></div></div></div>
 <div class="soc-panel"><div class="panel-head">Severity distribution <small>Rule-level classification</small></div><div class="panel-body">${['critical','high','medium','low'].map((k,i)=>`<div class="severity-row"><span class="name">${k[0].toUpperCase()+k.slice(1)}</span><div class="severity-track"><i style="width:${(counts[k]||0)/Math.max(1,total)*100}%;background:${['#cc596b','#db9965','#d1bc69','#6f9abe'][i]}"></i></div><strong>${a.available?counts[k]??0:'—'}</strong></div>`).join('')}</div></div></div>
 <div class="connection-strip"><strong>ALICE edge integration</strong><span>${l.available?`${l.total} records received from ${(l.nodes||[]).length} node(s)`:'Indexer audit stream unavailable'} · append-only delivery client</span><a href="#" onclick="goSoc('ledger');return false">Inspect audit stream →</a></div>
 ${latestEnterprise?`<div class="connection-strip"><strong>Latest governed request</strong><span>${esc(latestEnterprise.agent_id||latestRequest.agent_id||'Unknown agent')} · ${esc(latestRequest.action||'Unknown action')} · ${esc(latestOutcome)} · <span class="mono">${esc(latestId)}</span></span><a href="#" onclick="goSoc('enterprise');return false">Open enterprise requests →</a></div>`:''}
 <div class="soc-panel"><div class="panel-head">Priority detections <button class="soc-button" onclick="goSoc('hunt')">Open threat hunting →</button></div>${alertTable([...(a.rows||[])].sort((x,y)=>Number(y.rule?.level||0)-Number(x.rule?.level||0)).slice(0,7))}</div>
 <div class="source-note">${a.available?'Live query of wazuh-alerts-*; indexed content can include authored simulation events.':'Alert source unavailable. No synthetic fallback is shown.'} Updated ${esc(fmtTime(SOC.queried_at))}. EDR response execution is not connected in this demonstration.</div>`;
 $('s-hunt').innerHTML=socHeader('Threat hunting','Search the latest 300 indexed alerts; inspect rule, endpoint and raw evidence.')+
 `<div class="soc-toolbar"><input id="hunt-query" aria-label="Search alerts" placeholder="Search detection, host, rule or evidence…" value="${esc(huntText)}" oninput="huntText=this.value;filterHunt()"><select aria-label="Filter severity" onchange="huntSeverity=this.value;filterHunt()">${['all','critical','high','medium','low'].map(v=>`<option ${v===huntSeverity?'selected':''} value="${v}">${v==='all'?'All severities':v}</option>`).join('')}</select><span class="muted" id="hunt-count"></span></div><div class="soc-panel"><table class="soc-table"><thead><tr><th>Severity</th><th>Detection</th><th>Endpoint</th><th>Observed</th><th>Source</th></tr></thead><tbody id="hunt-rows"></tbody></table></div><p class="source-note">Investigation is read-only. No fabricated incident assignments, resolution status or response results.</p>`;
 filterHunt();renderEndpoints();renderVulnerabilities();renderMitre();renderCompliance();renderEnterprise();renderLedger();
}
function filterHunt(){const rows=(SOC.alerts.rows||[]).filter(a=>(huntSeverity==='all'||severity(a.rule?.level)===huntSeverity)&&JSON.stringify(a).toLowerCase().includes(huntText.toLowerCase()));$('hunt-rows').innerHTML=alertRows(rows);$('hunt-count').textContent=`${rows.length} / ${(SOC.alerts.rows||[]).length} loaded alerts`;}
function inspectAlert(i){const a=SOC.alerts.rows[i];if(!a)return;showSocDetail('Detection investigation',a.rule?.description||'Alert',`<div class="kv"><div>Severity</div><div>${pill(severity(a.rule?.level),severity(a.rule?.level))}</div><div>Rule</div><div>${esc(a.rule?.id)}</div><div>Endpoint</div><div>${esc(a.agent?.name||'Not supplied')}</div><div>Observed</div><div>${esc(fmtTime(a.timestamp))}</div><div>ATT&CK techniques</div><div>${esc((a.rule?.mitre?.id||[]).join(', ')||'Not mapped in source')}</div></div>`,a);}
function showSocDetail(kicker,title,body,raw){$('detail-body').innerHTML=`<div class="eyebrow">${esc(kicker)}</div><h2>${esc(title)}</h2>${body}<h3>Source evidence</h3><pre>${esc(JSON.stringify(raw,null,2))}</pre>`;$('detail').style.display='block';}
function renderEndpoints(){const rows=S?.endpoints||[];$('s-endpoints').innerHTML=socHeader('Endpoint security','Monitored assets across the DN-Hacks server-room and ALICE control environment.')+`<div class="connection-strip"><strong>Energy infrastructure asset inventory</strong><span>Hosts, cloud workloads, network infrastructure and protected control systems.</span></div><div class="soc-panel"><table class="soc-table"><thead><tr><th>Asset</th><th>Platform / address</th><th>Security group</th><th>Visibility</th><th>Detections loaded</th></tr></thead><tbody>${rows.map((e,i)=>`<tr><td><button class="link" onclick="inspectEndpoint(${i})">${esc(e.name)}</button><div class="subline">${esc(e.role)}</div></td><td>${esc(e.os)}<div class="subline mono">${esc(e.ip)} · scenario address</div></td><td>${esc(e.groups.join(', '))}</td><td>${pill('Monitored','live')}</td><td>${SOC.alerts.rows.filter(a=>a.agent?.name===e.name).length}</td></tr>`).join('')}</tbody></table></div><p class="source-note">Counts match indexed host names in the loaded alert window. ESP light output is a telemetry display and does not receive endpoint-response commands.</p>`;}
function inspectEndpoint(i){const e=S.endpoints[i], alerts=SOC.alerts.rows.filter(a=>a.agent?.name===e.name);showSocDetail('Endpoint investigation',e.name,`<p>${pill('Monitored','live')} ${esc(e.role)}</p><h3>Observed detection timeline</h3>${alerts.length?alerts.map(a=>`<p>${pill(severity(a.rule?.level),severity(a.rule?.level))} ${esc(fmtTime(a.timestamp))}<br>${esc(a.rule?.description)}</p>`).join(''):'<p>No matching detections in the loaded sample.</p>'}<h3>Response capabilities</h3><p class="muted">Isolation, scan and process termination are not connected. No endpoint command will be sent from this console.</p>`,e);}
function renderVulnerabilities(){const rows=SOC.posture?.vulnerabilities||[];$('s-vulnerabilities').innerHTML=socHeader('Vulnerability detection','Software exposure correlated from endpoint inventory and vulnerability intelligence.')+`<div class="kpis">${metric('ACTIVE FINDINGS',rows.length,'Loaded indexed findings','red')}${metric('CRITICAL / HIGH',rows.filter(r=>Number(r.rule?.level)>=9).length,'Prioritize remediation')}${metric('AFFECTED ENDPOINTS',new Set(rows.map(r=>r.agent?.name)).size,'Distinct monitored assets')}${metric('DATA SOURCE',SOC.alerts.available?'Wazuh indexer':'Unavailable','Inventory correlation','teal')}</div><div class="soc-panel"><table class="soc-table"><thead><tr><th>CVE</th><th>Package</th><th>Severity</th><th>Endpoint</th><th>Status</th></tr></thead><tbody>${rows.map((r,i)=>{const v=r.data.vulnerability,p=typeof v.package==='object'?v.package:{name:v.package,version:v.installed};return `<tr><td><button class="link" onclick="inspectAlert(${SOC.alerts.rows.indexOf(r)})">${esc(v.cve)}</button></td><td>${esc(p.name)}<div class="subline">installed ${esc(p.version)}</div></td><td>${pill(v.severity||severity(r.rule?.level),severity(r.rule?.level))}</td><td>${esc(r.agent?.name)}</td><td>${pill(v.status||'Active','high')}</td></tr>`}).join('')||'<tr><td colspan="5" class="empty">No vulnerability findings in the loaded interval.</td></tr>'}</tbody></table></div><p class="source-note">Scenario findings use Wazuh-shaped inventory correlation records. Validate packages and remediation against the real endpoint before acting.</p>`;}
function renderMitre(){const m=SOC.posture?.mitre||{techniques:{},tactics:{}},tech=Object.entries(m.techniques||{}),tactics=Object.entries(m.tactics||{});$('s-mitre').innerHTML=socHeader('MITRE ATT&CK','Indexed detections mapped to adversary tactics and techniques.')+`<div class="kpis">${metric('MAPPED EVENTS',tech.reduce((n,[,v])=>n+v,0),'Technique mappings in loaded alerts','blue')}${metric('TECHNIQUES',tech.length,'Distinct ATT&CK IDs')}${metric('TACTICS',tactics.length,'Distinct tactical objectives')}${metric('TOP TECHNIQUE',tech[0]?.[0]||'—',tech[0]?`${tech[0][1]} mapped events`:'No mappings','teal')}</div><div class="soc-grid"><div class="soc-panel"><div class="panel-head">Observed techniques</div><table class="soc-table"><thead><tr><th>Technique ID</th><th>Events</th></tr></thead><tbody>${tech.map(([k,v])=>`<tr><td class="mono">${esc(k)}</td><td>${v}</td></tr>`).join('')||'<tr><td colspan="2" class="empty">No ATT&CK mappings.</td></tr>'}</tbody></table></div><div class="soc-panel"><div class="panel-head">Tactic distribution</div><div class="panel-body">${tactics.map(([k,v])=>`<div class="severity-row"><span class="name attack-name">${esc(k)}</span><div class="severity-track"><i style="width:${Math.min(100,v/Math.max(1,...tactics.map(x=>x[1]))*100)}%;background:#38a4a2"></i></div><strong>${v}</strong></div>`).join('')||'<div class="empty">No mapped tactics.</div>'}</div></div></div><p class="source-note">Mappings come from the indexed rule metadata and support investigation; they do not establish attribution.</p>`;}
function renderCompliance(){const c=SOC.posture?.compliance||{rows:[],passed:0,failed:0,controls:{}},controls=Object.entries(c.controls||{});$('s-compliance').innerHTML=socHeader('Configuration & compliance','Security configuration assessment and NIST 800-53 evidence from monitored endpoints.')+`<div class="kpis">${metric('SCA PASSED',c.passed,'Loaded benchmark checks','teal')}${metric('SCA FAILED',c.failed,'Requires review','red')}${metric('NIST CONTROLS',controls.length,'Controls referenced by detections')}${metric('FIM EVENTS',(SOC.posture?.fim||[]).length,'File integrity changes observed','blue')}</div><div class="soc-grid"><div class="soc-panel"><div class="panel-head">Configuration assessment</div><table class="soc-table"><thead><tr><th>Result</th><th>Check</th><th>Endpoint</th><th>Policy</th></tr></thead><tbody>${(c.rows||[]).map(r=>{const s=r.data.sca;return `<tr><td>${pill(s.result,s.result==='passed'?'live':'high')}</td><td>${esc(s.check_id)}<div class="subline">${esc(s.remediation||'No remediation required')}</div></td><td>${esc(r.agent?.name)}</td><td>${esc(s.policy)}</td></tr>`}).join('')||'<tr><td colspan="4" class="empty">No SCA results in the loaded interval.</td></tr>'}</tbody></table></div><div class="soc-panel"><div class="panel-head">NIST 800-53 evidence coverage</div><div class="panel-body">${controls.slice(0,12).map(([k,v])=>`<div class="severity-row"><span class="name">${esc(k)}</span><div class="severity-track"><i style="width:${Math.min(100,v/Math.max(1,...controls.map(x=>x[1]))*100)}%;background:#619bd0"></i></div><strong>${v}</strong></div>`).join('')||'<div class="empty">No control mappings.</div>'}</div></div></div><p class="source-note">This view counts indexed evidence mappings. It is not a certification or an assessment of the real host configuration.</p>`;}
function renderEnterprise(){const e=SOC.enterprise||{rows:[]};$('s-enterprise').innerHTML=socHeader('Enterprise requests','Signed agent requests recorded by Wazuh before ALICE forwarding.')+`<div class="kpis">${metric('VERIFIED RECEIPTS',e.available?e.total:null,'Create-only Wazuh documents','teal')}${metric('LOADED REQUESTS',(e.rows||[]).length,'Latest enterprise submissions','blue')}${metric('DISTINCT AGENTS',new Set((e.rows||[]).map(r=>r.agent_id)).size,'Authenticated signing identities')}${metric('CHAIN ORDER','WAZUH → ALICE','Receipt precedes forwarding')}</div><div class="soc-panel"><table class="soc-table"><thead><tr><th>Received</th><th>Agent</th><th>Action</th><th>Target</th><th>Request ID</th></tr></thead><tbody>${(e.rows||[]).map((r,i)=>{const q=r.envelope?.request||{};return `<tr><td class="mono">${esc(fmtTime(r.received_at))}</td><td>${esc(r.agent_id||q.agent_id||'—')}</td><td>${esc(q.action||'—')}</td><td>${esc(q.target||'—')}</td><td><button class="link mono" onclick="inspectEnterprise(${i})">${esc(r.request_id||'—')}</button></td></tr>`}).join('')||'<tr><td colspan="5" class="empty">No enterprise receipts indexed yet.</td></tr>'}</tbody></table></div><p class="source-note">These are authenticated ingress receipts, not permission grants or proof of execution. Match the request ID to the edge audit stream for the ALICE decision and result.</p>`;}
function inspectEnterprise(i){const r=SOC.enterprise.rows[i];showSocDetail('Enterprise ingress receipt',r.request_id,`<div class="kv"><div>Agent</div><div>${esc(r.agent_id)}</div><div>Request digest</div><div class="mono">${esc(r.request_sha256)}</div><div>Received</div><div>${esc(fmtTime(r.received_at))}</div><div>Wazuh document</div><div class="mono">${esc(r.document_id)}</div></div>`,r);}
function renderLedger(){const l=SOC.ledger;$('s-ledger').innerHTML=socHeader('Edge audit stream','Actual records received by Wazuh from the Pi; separate from the authored scenario.')+`<div class="kpis">${metric('RECEIVED RECORDS',l.total,'All indexed history','teal')}${metric('REPORTING NODE IDENTITIES',l.available?l.nodes.length:null,'Seen in stored events; not live health')}${metric('LOADED RECORDS',l.rows.length,'Latest 100 by ledger sequence')}${metric('DELIVERY SOURCE',l.available?'Wazuh':'Unavailable','alice-ledger-v1')}</div><div class="soc-panel"><div class="panel-head">Decision and execution evidence ${pill(l.available?'Live index query':'Unavailable',l.available?'live':'unknown')}</div><table class="soc-table"><thead><tr><th>Seq</th><th>Event</th><th>Actor</th><th>Outcome</th><th>Request</th></tr></thead><tbody>${l.rows.map((r,i)=>`<tr><td class="mono">${r.sequence}</td><td><button class="link" onclick="inspectLedger(${i})">${esc(r.event_type)}</button></td><td>${esc(r.event?.attribution?.agent_id||r.event?.attribution?.actor_kind||'—')}</td><td>${esc(r.event?.detail?.outcome||r.event?.detail?.result||'—')}</td><td class="mono">${esc(r.request_id||'Uncorrelated')}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">No records available from Wazuh.</td></tr>'}</tbody></table></div><p class="source-note">Original event hashes and request IDs are retained. Large integers are displayed as decimal strings to preserve precision. Stored records are not new execution approvals. This view does not independently verify checkpoint signatures.</p>`;}
function inspectLedger(i){const r=SOC.ledger.rows[i];showSocDetail('Pi evidence record',r.event_type,`<div class="kv"><div>Node</div><div>${esc(r.node_id)}</div><div>Request</div><div>${esc(r.request_id||'—')}</div><div>Event hash</div><div style="word-break:break-all">${esc(r.event_hash)}</div></div>`,r);}
async function loadSoc(){if(socLoading)return;socLoading=true;try{const r=await fetch('/api/soc?window='+socWindow,{cache:'no-store'});if(!r.ok)throw Error();SOC=await r.json();}catch{SOC={queried_at:null,alerts:{available:false,rows:[],severity:{},trend:[]},enterprise:{available:false,rows:[],total:null},ledger:{available:false,rows:[],nodes:[],total:null},posture:{modules:{},mitre:{techniques:{},tactics:{}},compliance:{rows:[],passed:0,failed:0},vulnerabilities:[],fim:[]}};}finally{socLoading=false;}renderSoc();}
renderSoc();loadSoc();setInterval(loadSoc,5000);
