let SOC={alerts:{rows:[],severity:{},trend:[]},ledger:{rows:[],nodes:[]}}, socWindow='all', huntText='', huntSeverity='all';
const severity=l=>Number(l)>=12?'critical':Number(l)>=8?'high':Number(l)>=5?'medium':'low';
const pill=(text,type='unknown')=>`<span class="pill ${type}">${esc(text)}</span>`;
const fmtTime=t=>t?new Date(t).toLocaleString(): 'Not reported';
function goSoc(k){document.querySelector(`#nav button[data-k="${k}"]`)?.click();}
function socHeader(title,subtitle){return `<div class="soc-heading"><div><div class="eyebrow">Sentinel Air Force Base / Security operations</div><h2>${title}</h2><div class="muted">${subtitle}</div></div><div class="soc-controls"><select aria-label="Alert time range" onchange="socWindow=this.value;loadSoc()"><option value="all" ${socWindow==='all'?'selected':''}>All indexed history</option><option value="24h" ${socWindow==='24h'?'selected':''}>Last 24 hours</option><option value="7d" ${socWindow==='7d'?'selected':''}>Last 7 days</option></select><button class="soc-button" onclick="loadSoc()">↻ Refresh</button></div></div>`;}
function metric(label,value,hint,cls=''){return `<div class="metric ${cls}"><div class="label">${label}</div><div class="value">${value??'—'}</div><div class="hint">${hint}</div></div>`;}
function alertRows(rows){return rows.map(a=>{const i=SOC.alerts.rows.indexOf(a);return `<tr><td>${pill(severity(a.rule?.level),severity(a.rule?.level))}</td><td><button class="link" onclick="inspectAlert(${i})">${esc(a.rule?.description||'Untitled detection')}</button><div class="subline">Rule ${esc(a.rule?.id||'—')} · ${esc((a.rule?.groups||[]).slice(0,3).join(' / '))}</div></td><td>${esc(a.agent?.name||'Manager / unspecified')}</td><td class="mono">${esc(fmtTime(a.timestamp))}</td><td>${pill('Indexed','live')}</td></tr>`}).join('')||'<tr><td colspan="5" class="empty">No matching alerts. Adjust the query or time range.</td></tr>';}
function alertTable(rows){return `<table class="soc-table"><thead><tr><th>Severity</th><th>Detection</th><th>Endpoint</th><th>Observed</th><th>Source</th></tr></thead><tbody>${alertRows(rows)}</tbody></table>`;}
function renderSoc(){
 const a=SOC.alerts,l=SOC.ledger, counts=a.severity||{},total=a.total||0, trend=a.trend||[];
 const max=Math.max(1,...trend.map(x=>x.doc_count));
 const bars=trend.length?trend.map(b=>`<i style="height:${Math.max(3,b.doc_count/max*100)}%" title="${esc(b.key_as_string)}: ${b.doc_count} alerts"></i>`).join(''):'<div class="empty">No indexed events in this interval</div>';
 $('s-soc').innerHTML=socHeader('Security overview','Detection, endpoint visibility and autonomous-agent governance.')+
 `<div class="kpis">${metric('INDEXED ALERTS',a.available?a.total:null,'Selected time range · all severity levels','blue')}${metric('CRITICAL DETECTIONS',a.available?counts.critical:null,'Wazuh rule level 12–15','red')}${metric('EDGE AUDIT RECORDS',l.available?l.total:null,'Actual Pi uploads · all indexed history','teal')}${metric('DEMO ENDPOINT INVENTORY',S?.endpoints?.length??null,'Scenario assets · enrollment not verified')}</div>
 <div class="soc-grid"><div class="soc-panel"><div class="panel-head">Detection activity <small>Wazuh event-time histogram</small></div><div class="panel-body"><div class="plot" role="img" aria-label="Indexed alerts by time bucket">${bars}</div><div class="plot-label"><span>${esc(trend[0]?.key_as_string?.slice(0,16)||'No data')}</span><span>${esc(trend.at(-1)?.key_as_string?.slice(0,16)||'')}</span></div></div></div>
 <div class="soc-panel"><div class="panel-head">Severity distribution <small>Rule-level classification</small></div><div class="panel-body">${['critical','high','medium','low'].map((k,i)=>`<div class="severity-row"><span class="name">${k[0].toUpperCase()+k.slice(1)}</span><div class="severity-track"><i style="width:${(counts[k]||0)/Math.max(1,total)*100}%;background:${['#cc596b','#db9965','#d1bc69','#6f9abe'][i]}"></i></div><strong>${a.available?counts[k]??0:'—'}</strong></div>`).join('')}</div></div></div>
 <div class="connection-strip"><strong>ALICE edge integration</strong><span>${l.available?`${l.total} records received from ${(l.nodes||[]).length} node(s)`:'Indexer audit stream unavailable'} · append-only delivery client</span><a href="#" onclick="goSoc('ledger');return false">Inspect audit stream →</a></div>
 <div class="soc-panel"><div class="panel-head">Priority detections <button class="soc-button" onclick="goSoc('hunt')">Open threat hunting →</button></div>${alertTable([...(a.rows||[])].sort((x,y)=>Number(y.rule?.level||0)-Number(x.rule?.level||0)).slice(0,7))}</div>
 <div class="source-note">${a.available?'Live query of wazuh-alerts-*; indexed content can include authored simulation events.':'Alert source unavailable. No synthetic fallback is shown.'} Updated ${esc(fmtTime(SOC.queried_at))}. EDR response execution is not connected in this demonstration.</div>`;
 $('s-hunt').innerHTML=socHeader('Threat hunting','Search the latest 100 indexed alerts; inspect rule, endpoint and raw evidence.')+
 `<div class="soc-toolbar"><input id="hunt-query" aria-label="Search alerts" placeholder="Search detection, host, rule or evidence…" value="${esc(huntText)}" oninput="huntText=this.value;filterHunt()"><select aria-label="Filter severity" onchange="huntSeverity=this.value;filterHunt()">${['all','critical','high','medium','low'].map(v=>`<option ${v===huntSeverity?'selected':''} value="${v}">${v==='all'?'All severities':v}</option>`).join('')}</select><span class="muted" id="hunt-count"></span></div><div class="soc-panel"><table class="soc-table"><thead><tr><th>Severity</th><th>Detection</th><th>Endpoint</th><th>Observed</th><th>Source</th></tr></thead><tbody id="hunt-rows"></tbody></table></div><p class="source-note">Investigation is read-only. No fabricated incident assignments, resolution status or response results.</p>`;
 filterHunt();renderEndpoints();renderLedger();
}
function filterHunt(){const rows=(SOC.alerts.rows||[]).filter(a=>(huntSeverity==='all'||severity(a.rule?.level)===huntSeverity)&&JSON.stringify(a).toLowerCase().includes(huntText.toLowerCase()));$('hunt-rows').innerHTML=alertRows(rows);$('hunt-count').textContent=`${rows.length} / ${(SOC.alerts.rows||[]).length} loaded alerts`;}
function inspectAlert(i){const a=SOC.alerts.rows[i];if(!a)return;showSocDetail('Detection investigation',a.rule?.description||'Alert',`<div class="kv"><div>Severity</div><div>${pill(severity(a.rule?.level),severity(a.rule?.level))}</div><div>Rule</div><div>${esc(a.rule?.id)}</div><div>Endpoint</div><div>${esc(a.agent?.name||'Not supplied')}</div><div>Observed</div><div>${esc(fmtTime(a.timestamp))}</div><div>ATT&CK techniques</div><div>${esc((a.rule?.mitre?.id||[]).join(', ')||'Not mapped in source')}</div></div>`,a);}
function showSocDetail(kicker,title,body,raw){$('detail-body').innerHTML=`<div class="eyebrow">${esc(kicker)}</div><h2>${esc(title)}</h2>${body}<h3>Source evidence</h3><pre>${esc(JSON.stringify(raw,null,2))}</pre>`;$('detail').style.display='block';}
function renderEndpoints(){const rows=S?.endpoints||[];$('s-endpoints').innerHTML=socHeader('Endpoint security','Asset inventory and observed detections across the Sentinel demonstration.')+`<div class="connection-strip"><strong>Demo asset inventory</strong><span>Endpoint enrollment, sensor health and response permissions are not verified by this view.</span></div><div class="soc-panel"><table class="soc-table"><thead><tr><th>Asset</th><th>Platform / address</th><th>Security group</th><th>Visibility</th><th>Detections loaded</th></tr></thead><tbody>${rows.map((e,i)=>`<tr><td><button class="link" onclick="inspectEndpoint(${i})">${esc(e.name)}</button><div class="subline">${esc(e.role)}</div></td><td>${esc(e.os)}<div class="subline mono">${esc(e.ip)} · scenario address</div></td><td>${esc(e.groups.join(', '))}</td><td>${pill('Demo asset','demo')}</td><td>${SOC.alerts.rows.filter(a=>a.agent?.name===e.name).length}</td></tr>`).join('')}</tbody></table></div><p class="source-note">Counts match host names within the latest 100 loaded alerts. Zero matches does not establish endpoint health. ESP devices require an agreed telemetry adapter; they do not run a standard Wazuh host agent.</p>`;}
function inspectEndpoint(i){const e=S.endpoints[i], alerts=SOC.alerts.rows.filter(a=>a.agent?.name===e.name);showSocDetail('Endpoint investigation',e.name,`<p>${pill('Demo asset','demo')} ${esc(e.role)}</p><h3>Observed detection timeline</h3>${alerts.length?alerts.map(a=>`<p>${pill(severity(a.rule?.level),severity(a.rule?.level))} ${esc(fmtTime(a.timestamp))}<br>${esc(a.rule?.description)}</p>`).join(''):'<p>No matching detections in the loaded sample.</p>'}<h3>Response capabilities</h3><p class="muted">Isolation, scan and process termination are not connected. No endpoint command will be sent from this console.</p>`,e);}
function renderLedger(){const l=SOC.ledger;$('s-ledger').innerHTML=socHeader('Edge audit stream','Actual records received by Wazuh from the Pi; separate from the authored scenario.')+`<div class="kpis">${metric('RECEIVED RECORDS',l.total,'All indexed history','teal')}${metric('REPORTING NODE IDENTITIES',l.available?l.nodes.length:null,'Seen in stored events; not live health')}${metric('LOADED RECORDS',l.rows.length,'Latest 100 by ledger sequence')}${metric('DELIVERY SOURCE',l.available?'Wazuh':'Unavailable','alice-ledger-v1')}</div><div class="soc-panel"><div class="panel-head">Decision and execution evidence ${pill(l.available?'Live index query':'Unavailable',l.available?'live':'unknown')}</div><table class="soc-table"><thead><tr><th>Seq</th><th>Event</th><th>Actor</th><th>Outcome</th><th>Request</th></tr></thead><tbody>${l.rows.map((r,i)=>`<tr><td class="mono">${r.sequence}</td><td><button class="link" onclick="inspectLedger(${i})">${esc(r.event_type)}</button></td><td>${esc(r.event?.attribution?.agent_id||r.event?.attribution?.actor_kind||'—')}</td><td>${esc(r.event?.detail?.outcome||r.event?.detail?.result||'—')}</td><td class="mono">${esc(r.request_id||'Uncorrelated')}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">No records available from Wazuh.</td></tr>'}</tbody></table></div><p class="source-note">Original event hashes and request IDs are retained. Large integers are displayed as decimal strings to preserve precision. Stored records are not new execution approvals. This view does not independently verify checkpoint signatures.</p>`;}
function inspectLedger(i){const r=SOC.ledger.rows[i];showSocDetail('Pi evidence record',r.event_type,`<div class="kv"><div>Node</div><div>${esc(r.node_id)}</div><div>Request</div><div>${esc(r.request_id||'—')}</div><div>Event hash</div><div style="word-break:break-all">${esc(r.event_hash)}</div></div>`,r);}
async function loadSoc(){try{const r=await fetch('/api/soc?window='+socWindow,{cache:'no-store'});if(!r.ok)throw Error();SOC=await r.json();}catch{SOC={queried_at:null,alerts:{available:false,rows:[],severity:{},trend:[]},ledger:{available:false,rows:[],nodes:[],total:null}};}renderSoc();}
renderSoc();loadSoc();
